# Generated by Django 4.1.3 on 2022-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tenders',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='federal_law',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='purchase_stage',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='stack_technologies',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='FederalLaw',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='PurchaseStage',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
