# Generated by Django 4.1.1 on 2022-10-27 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_script', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tender',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tender',
            name='name',
            field=models.CharField(default='---', max_length=250),
        ),
        migrations.AlterField(
            model_name='tender',
            name='percentage_application_security',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='tender',
            name='placement_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tender',
            name='platform',
            field=models.CharField(blank=True, default='---', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tender',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tender',
            name='technical_specification',
            field=models.CharField(default='---', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tenderType',
            field=models.CharField(default='---', max_length=250),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AddField(
            model_name='keywords',
            name='searcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
