# Generated by Django 4.1.1 on 2022-11-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_script", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywords",
            name="keywords",
            field=models.JSONField(default=""),
        ),
    ]
