# Generated by Django 4.1.1 on 2022-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_script", "0002_alter_keywords_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywords",
            name="keywords",
            field=models.JSONField(default={"": ""}),
        ),
    ]
