# Generated by Django 4.1.3 on 2022-11-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_script', '0002_keywords_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
