# Generated by Django 4.1.1 on 2022-11-08 17:03

from django.db import migrations, models
import django.db.models.deletion
import parser_script.models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_script", "0002_keywords_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_definition_name",
                    models.CharField(max_length=250, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tender",
            name="platform_URL",
            field=models.CharField(default="---", max_length=250),
        ),
        migrations.CreateModel(
            name="TenderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to=parser_script.models.directory_path),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parser_script.tender",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tender",
            name="supplier_definition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parser_script.supplierdefinition",
            ),
        ),
    ]
