# Generated by Django 4.1.1 on 2022-11-08 17:23

from django.db import migrations, models
import parser_script.models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_script", "0003_supplierdefinition_tender_platform_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderdocument",
            name="title",
            field=models.CharField(default="---", max_length=250),
        ),
        migrations.AlterField(
            model_name="tenderdocument",
            name="document",
            field=models.FileField(
                null=True, upload_to=parser_script.models.directory_path
            ),
        ),
    ]
