# Generated by Django 4.1.1 on 2022-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_script", "0004_tenderdocument_title_alter_tenderdocument_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="number",
            field=models.CharField(default="---", max_length=250),
        ),
    ]
